# Generated by Django 2.1.15 on 2023-11-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyproducts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='babyproducts',
        ),
    ]
