# Generated by Django 5.0 on 2024-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyproducts', '0019_babyproduct_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
