# Generated by Django 5.0 on 2024-03-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyproducts', '0020_babyproduct_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyproduct',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
