# Generated by Django 2.1.15 on 2023-11-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyproducts', '0002_auto_20231106_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='babyproducts',
            new_name='BabyProduct',
        ),
    ]
